-- create table players(
--     id integer primary key,
--     first_name varchar(255),
--     username varchar(255),
--     account_id integer,
--     social_credits integer
-- );

-- insert into players (first_name, username, account_id, social_credits) 
-- values("Alexey", "GoldAlexGold", 202064123, 100);
-- insert into players (first_name, username, account_id, social_credits) 
-- values("Test", "TestUsername", 123456, 100);
-- insert into players (first_name, username, account_id, social_credits) 
-- values{
--     ("Alexey", "GoldAlexGold", 202064123, 100),
--     ("Test", "TestUsername", 123456, 100),
-- };
